### ISSUE TITLE
An example that is understandable

### ISSUE THREAD

**Issue by Zache** [howonlee/mertonon#7]
**Is your feature request related to a problem? Please describe.**
I think that maybe this is something very cool, but the extreme fakeness of the examples make it impossible for me to imagine it in a real context. 

**Describe the solution you'd like**
A more realistic example, doesn’t have to be a real organisation I guess that could be problematic. But if you replaced all the wizzbobs and foozicles with something more real then it would be easier to relate to. Maybe you could take a fictional but well known organisation and use that as an example. 

**Describe alternatives you've considered**
Getting a better imagination, I tried but failed

**Comment by howonlee** [comment]
SGTM. I'll probably work a more political and extended example next. Thanks for the feedback!

**Comment by howonlee** [comment]
I didn't replace the radical fakeness of the examples because I had writer's block for days but I did put in a new narrative bit, any comments?

**Comment by Zache** [comment]
I think I understand a little bit more now

**Comment by howonlee** [comment]
Cool beans.

Close out this issue if you think it's OK now or if you're sure you need like more specific fake examples do tell me. I will go at it again in a bit whether you think it's OK or not

**Comment by howonlee** [comment]
I am going to close this issue to make myself feel better
